name: render static website

on: 
  workflow_dispatch:

env:
  working_directory: .

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: feed content to backend
        working-directory: ${{ env.working_directory }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_PAGES }}
        shell: /bin/bash -e {0}
        run: |

          ls
          mkdir -p /tmp
          cd /tmp
          echo "--> Cloning to get main as a source for rendering the pages"
          git clone --branch main https://oauth2:$GITHUB_TOKEN@github.com/rovandep/glowing-octo-eureka.git
          mv glowing-octo-eureka main
          echo "--> Cloning to get gh-pages as a destination for rendered pages"
          git clone --branch gh-pages https://oauth2:$GITHUB_TOKEN@github.com/rovandep/glowing-octo-eureka.git
          mv glowing-octo-eureka gh-pages
          ls -al
          echo "--> Moving contents to hugo native folder structure"
          cp -R main/docs main/hugo-backend/content/
          cp -R main/images main/hugo-backend/static/
          cp -R main/sh main/hugo-backend/static/
          cp -R main/yaml main/hugo-backend/static/
          echo "--> Getting latest known working hugo binary with current framework"
          wget https://github.com/gohugoio/hugo/releases/download/v0.91.2/hugo_extended_0.91.2_Linux-64bit.tar.gz
          tar xfv hugo_0.91.2_Linux-64bit.tar.gz
          cd main/hugo-backend
          ls -al
          ../../hugo -D --config config/latest.toml
          cd
          cp -R main/site/latest/* gh-pages/
          cd gh-pages/
          git add --all .
          git commit -m "git action push"
          git push 
          cd ..
          rm -rf main gh-pages





